{
 "title": "cluster-resources-collect",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "集群 CPU Total (Cores)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum ( node:node_num_cpu:sum )" }
   ]
  },
  {
   "title": "集群 Mem Total (GiB)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum ( node_memory_MemTotal_bytes ) / 1024^3"
    }
   ]
  },
  {
   "title": "集群本地存储 Total (GiB)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum( node_filesystem_size_bytes{mountpoint=\"/host/root\"} ) /1024^3"
    }
   ]
  },
  {
   "title": "K8S 集群 POD Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count ( kube_pod_info )" }
   ]
  },
  {
   "title": "集群消耗CPU资源OS+APP",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum ( 1 - irate( node_cpu_seconds_total{mode=\"idle\"}[5m] ) )"
    }
   ]
  },
  {
   "title": "容器应用消耗资源CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum ( irate( container_cpu_usage_seconds_total[5m] ) ) * avg( node:node_num_cpu:sum )"
    }
   ]
  },
  {
   "title": "集群内存使用OS+APP+Buffer/Cache",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum( node_memory_MemTotal_bytes - node_memory_MemFree_bytes ) /1024^3"
    }
   ]
  },
  {
   "title": "容器应用消耗内存资源",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum( container_memory_usage_bytes /1024^3 )"
    }
   ]
  },
  {
   "title": "集群物理资源 CPU Mem 本地存储 Total",
   "type": "table",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum ( node:node_num_cpu:sum  ) by (node)"
    },
    {
     "expr": "sum( node_memory_MemTotal_bytes /1000^3 ) by (instance) "
    },
    {
     "expr": "sum ( node_filesystem_size_bytes{mountpoint=\"/host/root\"}  /1024^3 ) by (instance)"
    },
    {
     "expr": "count( kube_pod_info ) by (node)"
    }
   ]
  },
  {
   "title": "集群可用资源",
   "type": "table",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(  ( 1 - irate ( node_cpu_seconds_total{mode=\"idle\"}[5m]) ) * 2  ) by (instance)"
    },
    {
     "expr": "sum( node_memory_MemFree_bytes  /1024^3 ) by (instance)"
    },
    {
     "expr": "sum( node_memory_MemAvailable_bytes/1024^3 ) by (instance)"
    },
    {
     "expr": "sum( node_filesystem_free_bytes{mountpoint=\"/host/root\"}  /1024^3  )  by (instance)"
    },
    {
     "expr": "sum ( node_load1 ) by (instance)"
    },
    {
     "expr": "sum ( irate ( node_disk_reads_completed_total[5m] )  ) by (instance)"
    },
    {
     "expr": "sum ( irate ( node_disk_writes_completed_total[5m] )  ) by (instance)"
    }
   ]
  },
  {
   "title": "K8S 集群资源占用 CPU 内存 存储 POD",
   "type": "table",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum ( irate ( container_cpu_usage_seconds_total[5m] ) ) by (namespace)"
    },
    {
     "expr": "sum ( container_memory_usage_bytes / 1024^3 ) by (namespace)"
    },
    {
     "expr": "count ( kube_pod_info ) by (namespace)"
    },
    {
     "expr": " sum by (namespace) (kube_persistentvolumeclaim_resource_requests_storage_bytes / 1024^3)"
    }
   ]
  }
 ]
}